### ISSUE TITLE
Request: Read specific line

### ISSUE THREAD

**Issue by linecheck** [bitfocus/companion-module-generic-filereader#1]
Hi josephdadams and everybody else,

thank you very much for the module, I just wanted to ask, if it was possible to expand the module with the possibility to just read a specific line of a file. For example, I have a text file with:

42
3
92
24

Now I want to tell your module to read line 3 (or costum_variable_x) and result would be costum_variable_y (92).

So basically a new command "read line of file" with an additional variable. I already found a workaround by running an internal shell patch action and calling the windows powershell and (get-content), but I think a solution via a module would be nicer - also for non-programmers.

Thank you very much

Bastian

**Comment by josephdadams** [comment]
Are the files always utf8 encoded?

**Comment by linecheck** [comment]
I haven´t spent any thoughts on that. A "normal" windows txt-file seems to be UTF-8 as far as my quick research tells me. This would be my use-case, but I don´t know if other people will use it otherwise...

**Comment by josephdadams** [comment]
I won’t have time to do something like this unless it was paid work. But feel free to submit a pull request that does it. The module also needs to be converted to companion v3 api.

**Comment by josephdadams** [comment]
I did convert this module to the new v3 format, so there’s that!

**Comment by josephdadams** [comment]
@linecheck I've added this action for you. You can read a specific line of the configured file or a specific line of a custom file path. With every field supporting a custom variable value if needed.

Find someone who needs a hug and pass it on.
